<?xml version="1.0" encoding="utf-8"?><Database Name="PetopiaNew" Class="PetopiaLinkerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-828O4VC\SQLEXPRESS;Initial Catalog=PetopiaNew;Integrated Security=True" SettingsObjectName="Petopia.Properties.Settings" SettingsPropertyName="PetopiaNewConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Availability" Member="Availabilities">
    <Type Name="Availability">
      <Column Name="Availability_ID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Availability_Status" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="Availability_Item" Member="Items" ThisKey="Availability_ID" OtherKey="Availability_ID" Type="Item" />
    </Type>
  </Table>
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="Employee_ID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Employee_Name" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Employee_Username" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Employee_Password" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="Employee_Item" Member="Items" ThisKey="Employee_ID" OtherKey="Employee_ID" Type="Item" />
      <Association Name="Employee_Log" Member="Logs" ThisKey="Employee_ID" OtherKey="Employee_ID" Type="Log" />
      <Association Name="Employee_Pet" Member="Pets" ThisKey="Employee_ID" OtherKey="Employee_ID" Type="Pet" />
    </Type>
  </Table>
  <Table Name="dbo.IsAdopted" Member="IsAdopteds">
    <Type Name="IsAdopted">
      <Column Name="IsAdopted_ID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IsAdopted_Status" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="IsAdopted_Pet" Member="Pets" ThisKey="IsAdopted_ID" OtherKey="IsAdopted_ID" Type="Pet" />
    </Type>
  </Table>
  <Table Name="dbo.Item" Member="Items">
    <Type Name="Item">
      <Column Name="Item_ID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Item_Name" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Item_Price" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Item_Quantity" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="PetType_ID" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="ItemType_ID" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Availability_ID" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Employee_ID" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="Availability_Item" Member="Availability" ThisKey="Availability_ID" OtherKey="Availability_ID" Type="Availability" IsForeignKey="true" />
      <Association Name="Employee_Item" Member="Employee" ThisKey="Employee_ID" OtherKey="Employee_ID" Type="Employee" IsForeignKey="true" />
      <Association Name="ItemType_Item" Member="ItemType" ThisKey="ItemType_ID" OtherKey="ItemType_ID" Type="ItemType" IsForeignKey="true" />
      <Association Name="PetType_Item" Member="PetType" ThisKey="PetType_ID" OtherKey="PetType_ID" Type="PetType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ItemType" Member="ItemTypes">
    <Type Name="ItemType">
      <Column Name="ItemType_ID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ItemType_Name" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="ItemType_Item" Member="Items" ThisKey="ItemType_ID" OtherKey="ItemType_ID" Type="Item" />
    </Type>
  </Table>
  <Table Name="dbo.Logs" Member="Logs">
    <Type Name="Log">
      <Column Name="Logs_ID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Employee_ID" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Log_Time" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="LogStatus_ID" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="Employee_Log" Member="Employee" ThisKey="Employee_ID" OtherKey="Employee_ID" Type="Employee" IsForeignKey="true" />
      <Association Name="LogStatus_Log" Member="LogStatus" ThisKey="LogStatus_ID" OtherKey="LogStatus_ID" Type="LogStatus" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LogStatus" Member="LogStatus">
    <Type Name="LogStatus">
      <Column Name="LogStatus_ID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LogStatus_Type" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="LogStatus_Log" Member="Logs" ThisKey="LogStatus_ID" OtherKey="LogStatus_ID" Type="Log" />
    </Type>
  </Table>
  <Table Name="dbo.Pet" Member="Pets">
    <Type Name="Pet">
      <Column Name="Pet_ID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Pet_Name" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="PetType_ID" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Pet_Breed" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Pet_Weight" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Pet_Gender" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="IsAdopted_ID" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Employee_ID" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="Employee_Pet" Member="Employee" ThisKey="Employee_ID" OtherKey="Employee_ID" Type="Employee" IsForeignKey="true" />
      <Association Name="IsAdopted_Pet" Member="IsAdopted" ThisKey="IsAdopted_ID" OtherKey="IsAdopted_ID" Type="IsAdopted" IsForeignKey="true" />
      <Association Name="PetType_Pet" Member="PetType" ThisKey="PetType_ID" OtherKey="PetType_ID" Type="PetType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PetType" Member="PetTypes">
    <Type Name="PetType">
      <Column Name="PetType_ID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PetType_Name" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="PetType_Item" Member="Items" ThisKey="PetType_ID" OtherKey="PetType_ID" Type="Item" />
      <Association Name="PetType_Pet" Member="Pets" ThisKey="PetType_ID" OtherKey="PetType_ID" Type="Pet" />
    </Type>
  </Table>
</Database>